import React,{useEffect,useMemo,useState} from 'react';
import {Search,Music2,Download,CheckCircle2,ListMusic,Settings2,RefreshCw,Trash2,Pause,Play,ArrowUp,RotateCcw,ChevronLeft,ChevronRight,Plus,Wifi,WifiOff,Clock3,Gauge,FolderOpen,Image,Subtitles,Film,MoreHorizontal,ExternalLink,CheckSquare,Square,FileDown,Bug} from 'lucide-react';
import Settings from './Settings';

const api=async(url,opt)=>{const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||r.statusText);return d};
const cn=(...x)=>x.filter(Boolean).join(' ');
const bytes=n=>{n=Number(n||0);if(!n)return '—';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<3){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};
const time=s=>{if(!s)return '';s=Math.round(s);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};

function Badge({children,tone=''}){return <span className={cn('inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium',tone==='green'?'bg-emerald-500/15 text-emerald-300':tone==='red'?'bg-red-500/15 text-red-300':'bg-zinc-800 text-zinc-300')}>{children}</span>}
function Btn({children,onClick,primary=false,danger=false,disabled=false}){const [loading,setLoading]=useState(false);const handleClick=async e=>{if(disabled||loading)return;setLoading(true);try{return await onClick?.(e)}finally{setLoading(false)}};return <button type="button" disabled={disabled||loading} aria-busy={loading||undefined} onClick={handleClick} className={cn('inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm transition disabled:opacity-40',primary?'border-violet-500/40 bg-violet-600 text-white hover:bg-violet-500':danger?'border-red-500/20 bg-red-500/10 text-red-300 hover:bg-red-500/20':'border-white/10 bg-white/[.03] text-zinc-300 hover:bg-white/[.07]')}>{loading&&<RefreshCw size={14} className="animate-spin" aria-hidden="true"/>}{children}</button>}

function DownloadOptions({item}){const [useWireGuard,setUseWireGuard]=useState(()=>localStorage.getItem('music-wireguard')==='1');useEffect(()=>{const f=()=>setUseWireGuard(localStorage.getItem('music-wireguard')==='1');window.addEventListener('wireguard-setting',f);return()=>window.removeEventListener('wireguard-setting',f)},[]);const [type,setType]=useState('audio');const [sending,setSending]=useState(false);const [message,setMessage]=useState('');const submit=async e=>{e.preventDefault();if(sending)return;setSending(true);setMessage('');try{const fd=new FormData(e.currentTarget);await api('/api/download',{method:'POST',body:fd});setMessage('Added to queue');window.dispatchEvent(new CustomEvent('queue-updated'));}catch(err){setMessage(err.message||'Download failed')}finally{setSending(false)}};return <details className="mt-3 rounded-xl border border-white/10 bg-black/20 p-3"><summary className="cursor-pointer text-sm font-medium text-zinc-200">Download options</summary><form onSubmit={submit} className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">
<input type="hidden" name="source_url" value={item.url}/><input type="hidden" name="youtube_id" value={item.id}/><input type="hidden" name="title" value={item.title}/><input type="hidden" name="artists" value={item.channel}/>
<label className="field">Type<select name="download_type" value={type} onChange={e=>setType(e.target.value)}><option value="audio">Audio</option><option value="video">Video</option></select></label>
<label className="field">Format<select name="download_format">{(type==='audio'?['mp3','m4a','opus','wav','flac']:['any','mp4','ios']).map(x=><option key={x}>{x}</option>)}</select></label>
<label className="field">Quality<select name="download_quality">{(type==='audio'?['320','256','192','128','best']:['best','2160','1440','1080','720','480','360']).map(x=><option key={x}>{x}</option>)}</select></label>
{type==='video'&&<label className="field">Codec<select name="video_codec"><option>auto</option><option>h264</option><option>h265</option><option>av1</option><option>vp9</option></select></label>}
<label className="field">Folder<select name="download_folder"><option value="">Artist / Album</option><option>Music</option><option>YouTube</option><option>Videos</option></select></label>
<label className="field">Start<select name="auto_start"><option value="1">Now</option><option value="0">Pause</option></select></label>
<input type="hidden" name="wireguard" value={useWireGuard?'1':'0'}/><label className="field flex-row"><span>WireGuard</span><input type="checkbox" checked={useWireGuard} onChange={e=>{const v=e.target.checked?'1':'0';localStorage.setItem('music-wireguard',v);window.dispatchEvent(new Event('wireguard-setting'))}}/></label><label className="field flex-row"><span>Thumbnail</span><input type="checkbox" name="thumbnail" value="1" defaultChecked/></label>
{type==='video'&&<><label className="field flex-row"><span>Subtitle</span><input type="checkbox" name="subtitle" value="1"/></label><label className="field">Languages<input name="subtitle_lang" defaultValue="ja,en"/></label><label className="field">Subtitle mode<select name="subtitle_mode"><option value="prefer_manual">Manual preferred</option><option value="prefer_auto">Auto preferred</option><option value="manual_only">Manual only</option><option value="auto_only">Auto only</option></select></label><label className="field flex-row"><span>Split chapters</span><input type="checkbox" name="split_chapters" value="1"/></label></>}
<div className="col-span-full flex items-center gap-3"><Btn primary disabled={sending}>{sending?'Adding...':<><Download size={16}/> Download</>}</Btn>{message&&<span className="text-sm text-zinc-400">{message}</span>}</div></form></details>}

function SearchDebugPanel({traces}){return <div className="glass rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4"><div className="mb-3 flex items-center gap-2 font-semibold text-amber-200"><Bug size={16}/> Search debug trace</div><div className="space-y-3">{Object.entries(traces).map(([provider,trace])=><details key={provider} open className="rounded-xl border border-white/10 bg-black/20 p-3"><summary className="cursor-pointer text-sm font-medium">{provider} · {trace.duration_ms||0} ms</summary><div className="mt-3 space-y-2">{trace.steps?.map((x,i)=><div key={i} className="rounded-lg border border-white/5 bg-white/[.02] p-2 text-xs"><div className="flex items-center justify-between"><span className="font-semibold">{i+1}. {x.step}</span><Badge tone={x.status==='ok'||x.status==='connected'?'green':x.status==='error'?'red':''}>{x.status||'info'}</Badge></div>{x.error&&<div className="mt-1 text-red-300">{x.error}</div>}{x.detail&&typeof x.detail==='string'&&<div className="mt-1 text-zinc-400">{x.detail}</div>}{x.detail&&typeof x.detail==='object'&&<pre className="mt-1 max-h-48 overflow-auto whitespace-pre-wrap text-zinc-400">{JSON.stringify(x.detail,null,2)}</pre>}</div>)}{trace.provider_debug&&<div className="mt-2 rounded-lg border border-violet-500/20 bg-violet-500/5 p-2"><div className="mb-1 text-xs font-semibold text-violet-200">Provider HTTP diagnostics</div><pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs text-zinc-400">{JSON.stringify(trace.provider_debug,null,2)}</pre></div>}{trace.web_to_worker&&<div className="mt-2 rounded-lg border border-sky-500/20 bg-sky-500/5 p-2 text-xs text-zinc-400">Web → Worker: HTTP {trace.web_to_worker.http_status} · {trace.web_to_worker.duration_ms} ms · {trace.web_to_worker.worker_endpoint}</div>}</div></details>)}</div></div>}

function SearchResult({item,onFindYouTube}){return <div className="glass rounded-2xl p-4"><div className="flex gap-4"><img src={item.thumbnail||item.image} className="h-20 w-32 rounded-lg object-cover bg-zinc-800"/><div className="min-w-0 flex-1"><div className="font-semibold truncate">{item.title}</div><div className="mt-1 text-sm text-zinc-400">{item.channel||item.artists}{item.album?' · '+item.album:''}{item.duration? ' · '+time(item.duration):''}</div><div className="mt-2 flex gap-2"><a href={item.url} target="_blank" rel="noreferrer"><Btn><ExternalLink size={14}/> Open</Btn></a>{onFindYouTube&&<Btn onClick={()=>onFindYouTube(item)}><Search size={14}/> Find on YouTube</Btn>}</div>{!onFindYouTube&&<DownloadOptions item={item}/>}</div></div></div>}

function QueueRow({x,selected,onSelect,onLoad}){const summary=(x.download_type||x.source_type||'audio')+' · '+(x.download_quality||'best')+' / '+(x.video_codec&&x.video_codec!=='auto'?x.video_codec+' / ':'')+(x.download_format||'');return <div className="border-b border-white/5 px-4 py-3"><div className="grid min-w-[900px] grid-cols-[34px_2fr_100px_1.3fr_1.5fr_220px] items-center gap-3"><input type="checkbox" checked={selected} onChange={e=>onSelect(e.target.checked)}/><div className="min-w-0"><div className="truncate font-medium">{x.title}</div><div className="truncate text-xs text-zinc-500">{x.artists}</div></div><Badge tone={x.status==='failed'?'red':x.status==='downloading'?'green':''}>{x.status}</Badge><div className="text-xs text-zinc-400">{summary}</div><div><div className="mb-1 flex justify-between text-xs"><span>{x.progress||0}%</span><span className="text-zinc-500">{x.download_speed||'—'} {x.eta&&' · ETA '+x.eta}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-zinc-800"><div className="h-full bg-violet-500" style={{width:(x.progress||0)+'%'}}/></div></div><div className="flex gap-1.5">{x.status==='queued'&&<><Btn onClick={async()=>{await api('/api/queue/'+encodeURIComponent(x.spotify_id)+'/pause',{method:'POST'});onLoad()}}><Pause size={14}/></Btn><Btn onClick={async()=>{await api('/api/queue/prioritize/'+encodeURIComponent(x.spotify_id),{method:'POST'});onLoad()}}><ArrowUp size={14}/></Btn></>}{x.status==='paused'&&<Btn onClick={async()=>{await api('/api/queue/'+encodeURIComponent(x.spotify_id)+'/start',{method:'POST'});onLoad()}}><Play size={14}/></Btn>}{x.status==='failed'&&<Btn onClick={async()=>{await api('/api/retry/'+encodeURIComponent(x.spotify_id),{method:'POST'});onLoad()}}><RotateCcw size={14}/></Btn>}</div></div>{x.status==='failed'&&x.error&&<details className="mt-2 rounded-lg border border-red-500/20 bg-red-500/5 p-2"><summary className="cursor-pointer text-xs font-medium text-red-300">Download debug / error</summary><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap break-words text-xs text-zinc-400">{x.error}</pre></details>}</div>}

function App(){const [tab,setTab]=useState('downloading'),[showSettings,setShowSettings]=useState(false),[q,setQ]=useState(''),[source,setSource]=useState(()=>localStorage.getItem('music-search-source')||'all'),[wireguard,setWireguard]=useState(()=>localStorage.getItem('music-wireguard')==='1'),[debugMode,setDebugMode]=useState(()=>localStorage.getItem('music-search-debug')==='1'),[results,setResults]=useState({youtube:[],spotify:[],zingmp3:[],nhaccuatui:[]}),[searchErrors,setSearchErrors]=useState({}),[searchDebug,setSearchDebug]=useState({}),[page,setPage]=useState(1),[data,setData]=useState({jobs:[],history:[],playlists:[],services:null}),[sel,setSel]=useState(new Set()),[busy,setBusy]=useState(false);
 const load=async()=>{const [jobs,history,playlists,services]=await Promise.all([api('/api/jobs'),api('/api/history'),api('/api/playlists'),api('/api/services')]);setData({jobs:jobs.items||[],history:history.items||[],playlists:playlists.items||[],services})};
 useEffect(()=>{load();api('/api/settings/wireguard').then(d=>{const v=!!d.requested_enabled;setWireguard(v);localStorage.setItem('music-wireguard',v?'1':'0')}).catch(()=>{});const t=setInterval(load,5000);const refresh=()=>load();window.addEventListener('queue-updated',refresh);return()=>{clearInterval(t);window.removeEventListener('queue-updated',refresh)}},[]);
 const search=async(p=1)=>{if(!q.trim())return;setBusy(true);setSearchErrors({});if(debugMode)setSearchDebug({});localStorage.setItem('music-search-source',source);localStorage.setItem('music-search-debug',debugMode?'1':'0');try{const dbg=debugMode?'&debug=1':'';const tasks=[];if(source==='youtube'||source==='all')tasks.push(api('/api/search/youtube?q='+encodeURIComponent(q)+'&page='+p+'&limit=10&wireguard='+(wireguard?'1':'0')+dbg).then(d=>({type:'youtube',data:d})).catch(error=>({type:'youtube',error})));if(source==='zingmp3'||source==='all')tasks.push(api('/api/search/zingmp3?q='+encodeURIComponent(q)+'&page='+p+'&limit=10'+dbg).then(d=>({type:'zingmp3',data:d})).catch(error=>({type:'zingmp3',error})));if(source==='nhaccuatui'||source==='all')tasks.push(api('/api/search/nhaccuatui?q='+encodeURIComponent(q)+'&page='+p+'&limit=10'+dbg).then(d=>({type:'nhaccuatui',data:d})).catch(error=>({type:'nhaccuatui',error})));if(source==='spotify'||source==='all')tasks.push(api('/api/search/spotify?q='+encodeURIComponent(q)).then(d=>({type:'spotify',data:d})).catch(error=>({type:'spotify',error})));const settled=await Promise.all(tasks);const next={youtube:[],spotify:[],zingmp3:[],nhaccuatui:[]};const errors={};const traces={};for(const r of settled){if(r.error){errors[r.type]=r.error.message||'Search failed';continue}if(r.data?.debug)traces[r.type]=r.data.debug;if(r.type==='youtube'){next.youtube=r.data.items||[];if(r.data.error)errors.youtube=r.data.error}if(r.type==='zingmp3'){next.zingmp3=r.data.items||[];if(r.data.error)errors.zingmp3=r.data.error}if(r.type==='nhaccuatui'){next.nhaccuatui=r.data.items||[];if(r.data.error)errors.nhaccuatui=r.data.error}if(r.type==='spotify'){next.spotify=r.data.items||[];if(r.data.available===false)errors.spotify=r.data.error||'Spotify search unavailable'}}setResults(next);setSearchErrors(errors);setSearchDebug(traces);setPage(p)}finally{setBusy(false)}};
 const selected=[...sel];
 const findYouTube=(item)=>{setSource('youtube');setQ(item.artists+' - '+item.title);setTimeout(()=>search(1),0)};
 const selectAll=(ids)=>setSel(new Set(ids));
 const clearSelection=()=>setSel(new Set());
 const bulk=async(action)=>{if(!selected.length)return;const fd=new FormData();fd.append('action',action);fd.append('ids',selected.join(','));await fetch('/api/queue/bulk',{method:'POST',body:fd});setSel(new Set());load()};
 const queue=data.jobs.filter(x=>['downloading','queued','paused','pending_source','failed'].includes(x.status));
 const stats=useMemo(()=>({queue:queue.length,done:data.history.filter(x=>x.status==='completed').length,subs:data.playlists.length}),[queue,data]);
 return <div className="mx-auto max-w-[1500px] px-4 pb-12 md:px-8">
 <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 py-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-violet-600 p-2.5"><Music2/></div><div><h1 className="text-lg font-bold">Music Downloader</h1><p className="text-xs text-zinc-500">YouTube · Spotify · Zing MP3 · NhacCuaTui · Jellyfin</p></div></div><div className="flex items-center gap-2">{data.services&&<><Badge tone={data.services.worker.status==='online'?'green':'red'}>{data.services.worker.status==='online'?<Wifi size={13}/>:<WifiOff size={13}/>} Worker</Badge><Badge tone={data.services.scheduler.status==='online'?'green':'red'}>{data.services.scheduler.status==='online'?<Wifi size={13}/>:<WifiOff size={13}/>} Scheduler</Badge><Badge tone={data.services.wireguard?.status==='connected'?'green':(data.services.wireguard?.status==='connecting'||data.services.wireguard?.status==='disconnecting')?'':'red'}>{(data.services.wireguard?.status==='connected'||data.services.wireguard?.status==='connecting'||data.services.wireguard?.status==='disconnecting')?<Wifi size={13}/>:<WifiOff size={13}/>} WireGuard {data.services.wireguard?.status||'unknown'}</Badge></>}<Btn onClick={()=>setShowSettings(true)}>Settings</Btn><a href="/api/spotify/login"><Btn><Music2 size={15}/> Spotify Connect</Btn></a></div></header>
 {showSettings&&<Settings onClose={()=>setShowSettings(false)}/>}\n <section className="py-7"><div className="glass rounded-2xl p-3 shadow-2xl"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-zinc-500" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search(1)} placeholder="Search songs, artists or albums..." className="w-full rounded-xl border border-white/10 bg-black/20 py-2.5 pl-10 pr-3 outline-none focus:border-violet-500"/></div><select value={source} onChange={e=>setSource(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-zinc-200 outline-none"><option value="all">All</option><option value="spotify">Spotify</option><option value="youtube">YouTube</option><option value="zingmp3">Zing MP3</option><option value="nhaccuatui">NhacCuaTui</option></select><Btn onClick={()=>{const v=!debugMode;setDebugMode(v);localStorage.setItem('music-search-debug',v?'1':'0')}}><Bug size={15}/> Debug {debugMode?'ON':'OFF'}</Btn><Btn primary onClick={()=>search(1)} disabled={busy}><Search size={17}/> Search</Btn></div></div></section>
 {(busy||results.youtube.length||results.spotify.length||results.zingmp3.length||results.nhaccuatui.length||Object.keys(searchErrors).length>0)&&<section className="space-y-5">
 {busy&&<div className="glass rounded-2xl border border-violet-500/20 bg-violet-500/5 p-6"><div className="flex items-center justify-center gap-3 text-sm text-zinc-300"><RefreshCw size={20} className="animate-spin text-violet-400"/><span>Searching ... Please wait</span></div></div>} {debugMode&&Object.keys(searchDebug).length>0&&<SearchDebugPanel traces={searchDebug}/>}

 {!busy&&searchErrors.spotify&&<div className="rounded-2xl border border-amber-500/20 bg-amber-500/10 p-4 text-sm text-amber-200"><div className="font-semibold">Spotify search unavailable</div><div className="mt-1 text-amber-200/80">{searchErrors.spotify}</div><div className="mt-2 text-xs text-zinc-400">You can continue searching YouTube without Spotify.</div></div>}
 {results.spotify.length>0&&<div className="space-y-3"><h2 className="font-semibold">Spotify results</h2>{results.spotify.map(x=><SearchResult key={x.id} item={x} onFindYouTube={findYouTube}/>)}</div>}
 {results.zingmp3.length>0&&<div className="space-y-3"><h2 className="font-semibold">Zing MP3 results</h2>{results.zingmp3.map(x=><SearchResult key={x.id} item={x}/>)}</div>}{results.nhaccuatui.length>0&&<div className="space-y-3"><h2 className="font-semibold">NhacCuaTui results</h2>{results.nhaccuatui.map(x=><SearchResult key={x.id} item={x}/>)}</div>}{results.youtube.length>0&&<div className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">YouTube results</h2><div className="flex gap-2">{page>1&&<Btn onClick={()=>search(page-1)}><ChevronLeft size={15}/> Prev</Btn>}<span className="px-2 py-2 text-sm text-zinc-500">Page {page}</span><Btn onClick={()=>search(page+1)}><ChevronRight size={15}/> Next</Btn></div></div>{results.youtube.map(x=><SearchResult key={x.id} item={x}/>)}</div>}
 </section>}
 <section className="mt-8"><div className="grid grid-cols-3 gap-3">{[['downloading',Download,stats.queue,'Queue'],['completed',CheckCircle2,stats.done,'Completed'],['subscriptions',ListMusic,stats.subs,'Subscriptions']].map(([id,I,n,label])=><button key={id} onClick={()=>setTab(id)} className={cn('rounded-2xl border p-4 text-left transition',tab===id?'border-violet-500/40 bg-violet-500/10':'border-white/5 bg-white/[.02] hover:bg-white/[.05]')}><div className="flex items-center justify-between"><I size={18} className="text-violet-300"/><span className="text-2xl font-bold">{n}</span></div><div className="mt-2 text-sm text-zinc-400">{label}</div></button>)}</div></section>
 {tab==='downloading'&&<section className="glass mt-4 overflow-hidden rounded-2xl"><Toolbar title="Downloading" icon={Download} count={queue.length} onRefresh={load} actions={<><Btn onClick={()=>selectAll(queue.map(x=>x.spotify_id))} disabled={!queue.length}><CheckSquare size={15}/> Select all</Btn><Btn onClick={clearSelection} disabled={!selected.length}><Square size={15}/> Clear</Btn><Btn onClick={()=>bulk('clear_selected')} disabled={!selected.length}><Trash2 size={15}/> Cancel selected</Btn><Btn onClick={()=>bulk('download_selected')} disabled={!selected.length}><Download size={15}/> Download selected</Btn></>}/><div className="scrollbar overflow-x-auto"><div className="grid min-w-[900px] grid-cols-[34px_2fr_100px_1.3fr_1.5fr_220px] gap-3 border-b border-white/5 bg-black/10 px-4 py-2 text-xs uppercase tracking-wide text-zinc-500"><div></div><div>Video</div><div>Status</div><div>Format</div><div>Progress / Speed</div><div>Actions</div></div>{queue.map(x=><QueueRow key={x.spotify_id} x={x} selected={sel.has(x.spotify_id)} onSelect={v=>setSel(s=>{const n=new Set(s);v?n.add(x.spotify_id):n.delete(x.spotify_id);return n})} onLoad={load}/>)}</div></section>}
 {tab==='completed'&&<section className="glass mt-4 overflow-hidden rounded-2xl"><Toolbar title="Completed" icon={CheckCircle2} count={data.history.length} onRefresh={load} actions={<><Btn onClick={()=>selectAll(data.history.map(x=>x.spotify_id))} disabled={!data.history.length}><CheckSquare size={15}/> Select all</Btn><Btn onClick={clearSelection} disabled={!selected.length}><Square size={15}/> Clear</Btn><Btn onClick={()=>bulk('clear_selected')} disabled={!selected.length}><Trash2 size={15}/> Clear selected</Btn><Btn onClick={()=>bulk('clear_completed')}><CheckCircle2 size={15}/> Clear completed</Btn><Btn onClick={()=>bulk('clear_failed')}><Trash2 size={15}/> Clear failed</Btn><Btn onClick={()=>bulk('retry_failed')}><RotateCcw size={15}/> Retry failed</Btn></>}/><div className="scrollbar overflow-x-auto">{data.history.map(x=><div key={x.spotify_id} className="grid min-w-[900px] grid-cols-[34px_2fr_100px_1.5fr_110px_160px_120px] items-center gap-3 border-b border-white/5 px-4 py-3"><input type="checkbox" checked={sel.has(x.spotify_id)} onChange={e=>setSel(s=>{const n=new Set(s);e.target.checked?n.add(x.spotify_id):n.delete(x.spotify_id);return n})}/><div><div className="truncate font-medium">{x.title}</div><div className="text-xs text-zinc-500">{x.artists}</div></div><Badge tone={x.status==='failed'?'red':'green'}>{x.status}</Badge><div className="text-xs text-zinc-400">{x.download_quality||'best'} / {x.video_codec&&x.video_codec!=='auto'?x.video_codec+' / ':''}{x.download_format||''}</div><div className="text-xs">{bytes(x.total_bytes)}</div><div className="text-xs text-zinc-500">{x.updated_at}</div><div className="flex gap-1.5">{x.status==='completed'&&<><a href={"/api/files/"+encodeURIComponent(x.spotify_id)+"?download=1"}><Btn><Download size={14}/> Download</Btn></a><a href={"/api/files/"+encodeURIComponent(x.spotify_id)+"?download=0"} target="_blank" rel="noreferrer"><Btn><ExternalLink size={14}/> Open</Btn></a></>}{x.status!=='completed'&&x.source_url&&<a href={x.source_url} target="_blank" rel="noreferrer"><Btn><ExternalLink size={14}/> Source</Btn></a>}<Btn onClick={async()=>{await api('/api/retry/'+encodeURIComponent(x.spotify_id),{method:'POST'});load()}}><RotateCcw size={14}/></Btn></div></div>)}</div></section>}
 {tab==='subscriptions'&&<section className="glass mt-4 overflow-hidden rounded-2xl"><Toolbar title="Subscriptions" icon={ListMusic} count={data.playlists.length} onRefresh={load} actions={<><Btn onClick={()=>selectAll(data.playlists.map(x=>x.spotify_id))} disabled={!data.playlists.length}><CheckSquare size={15}/> Select all</Btn><Btn onClick={clearSelection} disabled={!selected.length}><Square size={15}/> Clear</Btn><Btn onClick={async()=>{for(const p of data.playlists)if(p.enabled)await api('/api/playlists/'+encodeURIComponent(p.spotify_id)+'/sync-manual',{method:'POST'});load()}}><RefreshCw size={15}/> Check all now</Btn><Btn onClick={async()=>{for(const id of selected)await api('/api/playlists/'+encodeURIComponent(id)+'/sync-manual',{method:'POST'});load()} } disabled={!selected.length}><RefreshCw size={15}/> Check selected</Btn><Btn danger onClick={async()=>{for(const id of selected)await api('/api/playlists/'+encodeURIComponent(id),{method:'DELETE'});setSel(new Set());load()}} disabled={!selected.length}><Trash2 size={15}/> Delete selected</Btn></>}/><div>{data.playlists.map(p=><div key={p.spotify_id} className="flex flex-wrap items-center gap-4 border-b border-white/5 px-4 py-4"><input type="checkbox" checked={sel.has(p.spotify_id)} onChange={e=>setSel(s=>{const n=new Set(s);e.target.checked?n.add(p.spotify_id):n.delete(p.spotify_id);return n})}/><div className="min-w-[260px] flex-1"><div className="font-medium">{p.name}</div><div className="text-xs text-zinc-500">{p.url}</div></div><a href={p.url} target="_blank" rel="noreferrer"><Btn><ExternalLink size={14}/> Open</Btn></a><Badge tone={p.enabled?'green':'red'}>{p.enabled?'enabled':'disabled'}</Badge><span className="text-xs text-zinc-500">Last sync: {p.last_sync||'never'}</span><Btn onClick={async()=>{await api('/api/playlists/'+encodeURIComponent(p.spotify_id)+'/sync-manual',{method:'POST'});load()}}><RefreshCw size={14}/></Btn></div>)}</div></section>}
 </div>}
function Toolbar({title:Title,icon:Icon,count,onRefresh,actions}){return <div className="flex flex-wrap items-center gap-3 border-b border-white/10 p-4"><div className="flex items-center gap-2 mr-2"><Icon size={18} className="text-violet-300"/><span className="font-semibold">{Title}</span><Badge>{count}</Badge></div>{actions}<div className="ml-auto"><Btn onClick={onRefresh}><RefreshCw size={15}/></Btn></div></div>}
export default App;
