import React,{useEffect,useMemo,useState} from 'react';
import {Search,Music2,Download,CheckCircle2,ListMusic,Settings2,RefreshCw,Trash2,Pause,Play,ArrowUp,RotateCcw,ChevronLeft,ChevronRight,Plus,Wifi,WifiOff,Clock3,Gauge,FolderOpen,Image,Subtitles,Film,MoreHorizontal} from 'lucide-react';

const api=async(url,opt)=>{const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||r.statusText);return d};
const cn=(...x)=>x.filter(Boolean).join(' ');
const bytes=n=>{n=Number(n||0);if(!n)return '—';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<3){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};
const time=s=>{if(!s)return '';s=Math.round(s);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};

function Badge({children,tone=''}){return <span className={cn('inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium',tone==='green'?'bg-emerald-500/15 text-emerald-300':tone==='red'?'bg-red-500/15 text-red-300':'bg-zinc-800 text-zinc-300')}>{children}</span>}
function Btn({children,onClick,primary=false,danger=false,disabled=false}){return <button disabled={disabled} onClick={onClick} className={cn('inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm transition disabled:opacity-40',primary?'border-violet-500/40 bg-violet-600 text-white hover:bg-violet-500':danger?'border-red-500/20 bg-red-500/10 text-red-300 hover:bg-red-500/20':'border-white/10 bg-white/[.03] text-zinc-300 hover:bg-white/[.07]')}>{children}</button>}

function DownloadOptions({item}){const [type,setType]=useState('audio');return <details className="mt-3 rounded-xl border border-white/10 bg-black/20 p-3"><summary className="cursor-pointer text-sm font-medium text-zinc-200">Download options</summary><form method="post" action="/api/download" className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">
<input type="hidden" name="source_url" value={item.url}/><input type="hidden" name="youtube_id" value={item.id}/><input type="hidden" name="title" value={item.title}/><input type="hidden" name="artists" value={item.channel}/>
<label className="field">Type<select name="download_type" value={type} onChange={e=>setType(e.target.value)}><option value="audio">Audio</option><option value="video">Video</option></select></label>
<label className="field">Format<select name="download_format">{(type==='audio'?['mp3','m4a','opus','wav','flac']:['any','mp4','ios']).map(x=><option key={x}>{x}</option>)}</select></label>
<label className="field">Quality<select name="download_quality">{(type==='audio'?['320','256','192','128','best']:['best','2160','1440','1080','720','480','360']).map(x=><option key={x}>{x}</option>)}</select></label>
{type==='video'&&<label className="field">Codec<select name="video_codec"><option>auto</option><option>h264</option><option>h265</option><option>av1</option><option>vp9</option></select></label>}
<label className="field">Folder<select name="download_folder"><option value="">Artist / Album</option><option>Music</option><option>YouTube</option><option>Videos</option></select></label>
<label className="field">Start<select name="auto_start"><option value="1">Now</option><option value="0">Pause</option></select></label>
<label className="field flex-row"><span>Thumbnail</span><input type="checkbox" name="thumbnail" value="1" defaultChecked/></label>
{type==='video'&&<><label className="field flex-row"><span>Subtitle</span><input type="checkbox" name="subtitle" value="1"/></label><label className="field">Languages<input name="subtitle_lang" defaultValue="ja,en"/></label><label className="field">Subtitle mode<select name="subtitle_mode"><option value="prefer_manual">Manual preferred</option><option value="prefer_auto">Auto preferred</option><option value="manual_only">Manual only</option><option value="auto_only">Auto only</option></select></label><label className="field flex-row"><span>Split chapters</span><input type="checkbox" name="split_chapters" value="1"/></label></>}
<div className="col-span-full"><Btn primary><Download size={16}/> Download</Btn></div></form></details>}

function SearchResult({item}){return <div className="glass rounded-2xl p-4"><div className="flex gap-4"><img src={item.thumbnail} className="h-20 w-32 rounded-lg object-cover bg-zinc-800"/><div className="min-w-0 flex-1"><div className="font-semibold truncate">{item.title}</div><div className="mt-1 text-sm text-zinc-400">{item.channel} · {time(item.duration)}</div><DownloadOptions item={item}/></div></div></div>}

function QueueRow({x,selected,onSelect,onLoad}){const summary=(x.download_type||x.source_type||'audio')+' · '+(x.download_quality||'best')+' / '+(x.video_codec&&x.video_codec!=='auto'?x.video_codec+' / ':'')+(x.download_format||'');return <div className="grid min-w-[900px] grid-cols-[34px_2fr_100px_1.3fr_1.5fr_220px] items-center gap-3 border-b border-white/5 px-4 py-3"><input type="checkbox" checked={selected} onChange={e=>onSelect(e.target.checked)}/><div className="min-w-0"><div className="truncate font-medium">{x.title}</div><div className="truncate text-xs text-zinc-500">{x.artists}</div></div><Badge tone={x.status==='failed'?'red':x.status==='downloading'?'green':''}>{x.status}</Badge><div className="text-xs text-zinc-400">{summary}</div><div><div className="mb-1 flex justify-between text-xs"><span>{x.progress||0}%</span><span className="text-zinc-500">{x.download_speed||''} {x.eta&&'ETA '+x.eta}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-zinc-800"><div className="h-full bg-violet-500" style={{width:(x.progress||0)+'%'}}/></div></div><div className="flex gap-1.5">{x.status==='queued'&&<><Btn onClick={async()=>{await api('/api/queue/'+encodeURIComponent(x.spotify_id)+'/pause',{method:'POST'});onLoad()}}><Pause size={14}/></Btn><Btn onClick={async()=>{await api('/api/queue/prioritize/'+encodeURIComponent(x.spotify_id),{method:'POST'});onLoad()}}><ArrowUp size={14}/></Btn></>}{x.status==='paused'&&<Btn onClick={async()=>{await api('/api/queue/'+encodeURIComponent(x.spotify_id)+'/start',{method:'POST'});onLoad()}}><Play size={14}/></Btn>}{x.status==='failed'&&<Btn onClick={async()=>{await api('/api/retry/'+encodeURIComponent(x.spotify_id),{method:'POST'});onLoad()}}><RotateCcw size={14}/></Btn>}</div></div>}

function App(){const [tab,setTab]=useState('downloading'),[q,setQ]=useState(''),[results,setResults]=useState([]),[page,setPage]=useState(1),[data,setData]=useState({jobs:[],history:[],playlists:[],services:null}),[sel,setSel]=useState(new Set()),[busy,setBusy]=useState(false);
 const load=async()=>{const [jobs,history,playlists,services]=await Promise.all([api('/api/jobs'),api('/api/history'),api('/api/playlists'),api('/api/services')]);setData({jobs:jobs.items||[],history:history.items||[],playlists:playlists.items||[],services})};
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 const search=async(p=1)=>{if(!q.trim())return;setBusy(true);try{const d=await api('/api/search/youtube?q='+encodeURIComponent(q)+'&page='+p+'&limit=10');setResults(d.items||[]);setPage(d.page||p)}finally{setBusy(false)}};
 const selected=[...sel];
 const bulk=async(action)=>{if(!selected.length)return;const fd=new FormData();fd.append('action',action);fd.append('ids',selected.join(','));await fetch('/api/queue/bulk',{method:'POST',body:fd});setSel(new Set());load()};
 const queue=data.jobs.filter(x=>['downloading','queued','paused','pending_source','failed'].includes(x.status));
 const stats=useMemo(()=>({queue:queue.length,done:data.history.filter(x=>x.status==='completed').length,subs:data.playlists.length}),[queue,data]);
 return <div className="mx-auto max-w-[1500px] px-4 pb-12 md:px-8">
 <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 py-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-violet-600 p-2.5"><Music2/></div><div><h1 className="text-lg font-bold">Music Downloader</h1><p className="text-xs text-zinc-500">YouTube · Spotify metadata · Jellyfin</p></div></div><div className="flex items-center gap-2">{data.services&&<><Badge tone={data.services.worker.status==='online'?'green':'red'}>{data.services.worker.status==='online'?<Wifi size={13}/>:<WifiOff size={13}/>} Worker</Badge><Badge tone={data.services.scheduler.status==='online'?'green':'red'}>{data.services.scheduler.status==='online'?<Wifi size={13}/>:<WifiOff size={13}/>} Scheduler</Badge></>}<a href="/api/spotify/login"><Btn><Music2 size={15}/> Spotify Connect</Btn></a></div></header>
 <section className="py-7"><div className="glass rounded-2xl p-3 shadow-2xl"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-zinc-500" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search(1)} placeholder="Search songs, artists, albums or YouTube videos..." className="w-full rounded-xl border border-white/10 bg-black/20 py-2.5 pl-10 pr-3 outline-none focus:border-violet-500"/></div><Btn primary onClick={()=>search(1)} disabled={busy}><Search size={17}/> Search</Btn></div></div></section>
 {results.length>0&&<section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">YouTube results</h2><div className="flex gap-2">{page>1&&<Btn onClick={()=>search(page-1)}><ChevronLeft size={15}/> Prev</Btn>}<span className="px-2 py-2 text-sm text-zinc-500">Page {page}</span><Btn onClick={()=>search(page+1)}><ChevronRight size={15}/> Next</Btn></div></div>{results.map(x=><SearchResult key={x.id} item={x}/>)}</section>}
 <section className="mt-8"><div className="grid grid-cols-3 gap-3">{[['downloading',Download,stats.queue,'Queue'],['completed',CheckCircle2,stats.done,'Completed'],['subscriptions',ListMusic,stats.subs,'Subscriptions']].map(([id,I,n,label])=><button key={id} onClick={()=>setTab(id)} className={cn('rounded-2xl border p-4 text-left transition',tab===id?'border-violet-500/40 bg-violet-500/10':'border-white/5 bg-white/[.02] hover:bg-white/[.05]')}><div className="flex items-center justify-between"><I size={18} className="text-violet-300"/><span className="text-2xl font-bold">{n}</span></div><div className="mt-2 text-sm text-zinc-400">{label}</div></button>)}</div></section>
 {tab==='downloading'&&<section className="glass mt-4 overflow-hidden rounded-2xl"><Toolbar title="Downloading" icon={Download} count={queue.length} onRefresh={load} actions={<><Btn onClick={()=>bulk('clear_selected')} disabled={!selected.length}><Trash2 size={15}/> Cancel selected</Btn><Btn onClick={()=>bulk('download_selected')} disabled={!selected.length}><Download size={15}/> Download selected</Btn></>}/><div className="scrollbar overflow-x-auto"><div className="grid min-w-[900px] grid-cols-[34px_2fr_100px_1.3fr_1.5fr_220px] gap-3 border-b border-white/5 bg-black/10 px-4 py-2 text-xs uppercase tracking-wide text-zinc-500"><div></div><div>Video</div><div>Status</div><div>Format</div><div>Progress / Speed</div><div>Actions</div></div>{queue.map(x=><QueueRow key={x.spotify_id} x={x} selected={sel.has(x.spotify_id)} onSelect={v=>setSel(s=>{const n=new Set(s);v?n.add(x.spotify_id):n.delete(x.spotify_id);return n})} onLoad={load}/>)}</div></section>}
 {tab==='completed'&&<section className="glass mt-4 overflow-hidden rounded-2xl"><Toolbar title="Completed" icon={CheckCircle2} count={data.history.length} onRefresh={load} actions={<><Btn onClick={()=>bulk('clear_selected')} disabled={!selected.length}><Trash2 size={15}/> Clear selected</Btn><Btn onClick={()=>bulk('clear_completed')}><CheckCircle2 size={15}/> Clear completed</Btn><Btn onClick={()=>bulk('clear_failed')}><Trash2 size={15}/> Clear failed</Btn><Btn onClick={()=>bulk('retry_failed')}><RotateCcw size={15}/> Retry failed</Btn></>}/><div className="scrollbar overflow-x-auto">{data.history.map(x=><div key={x.spotify_id} className="grid min-w-[900px] grid-cols-[34px_2fr_100px_1.5fr_110px_160px_120px] items-center gap-3 border-b border-white/5 px-4 py-3"><input type="checkbox" checked={sel.has(x.spotify_id)} onChange={e=>setSel(s=>{const n=new Set(s);e.target.checked?n.add(x.spotify_id):n.delete(x.spotify_id);return n})}/><div><div className="truncate font-medium">{x.title}</div><div className="text-xs text-zinc-500">{x.artists}</div></div><Badge tone={x.status==='failed'?'red':'green'}>{x.status}</Badge><div className="text-xs text-zinc-400">{x.download_quality||'best'} / {x.video_codec&&x.video_codec!=='auto'?x.video_codec+' / ':''}{x.download_format||''}</div><div className="text-xs">{bytes(x.total_bytes)}</div><div className="text-xs text-zinc-500">{x.updated_at}</div><Btn onClick={async()=>{await api('/api/retry/'+encodeURIComponent(x.spotify_id),{method:'POST'});load()}}><RotateCcw size={14}/></Btn></div>)}</div></section>}
 {tab==='subscriptions'&&<section className="glass mt-4 overflow-hidden rounded-2xl"><Toolbar title="Subscriptions" icon={ListMusic} count={data.playlists.length} onRefresh={load} actions={<><Btn onClick={async()=>{for(const p of data.playlists)if(p.enabled)await api('/api/playlists/'+encodeURIComponent(p.spotify_id)+'/sync-manual',{method:'POST'});load()}}><RefreshCw size={15}/> Check all now</Btn><Btn onClick={async()=>{for(const id of selected)await api('/api/playlists/'+encodeURIComponent(id)+'/sync-manual',{method:'POST'});load()} } disabled={!selected.length}><RefreshCw size={15}/> Check selected</Btn><Btn danger onClick={async()=>{for(const id of selected)await api('/api/playlists/'+encodeURIComponent(id),{method:'DELETE'});setSel(new Set());load()}} disabled={!selected.length}><Trash2 size={15}/> Delete selected</Btn></>}/><div>{data.playlists.map(p=><div key={p.spotify_id} className="flex flex-wrap items-center gap-4 border-b border-white/5 px-4 py-4"><input type="checkbox" checked={sel.has(p.spotify_id)} onChange={e=>setSel(s=>{const n=new Set(s);e.target.checked?n.add(p.spotify_id):n.delete(p.spotify_id);return n})}/><div className="min-w-[260px] flex-1"><div className="font-medium">{p.name}</div><div className="text-xs text-zinc-500">{p.url}</div></div><Badge tone={p.enabled?'green':'red'}>{p.enabled?'enabled':'disabled'}</Badge><span className="text-xs text-zinc-500">Last sync: {p.last_sync||'never'}</span><Btn onClick={async()=>{await api('/api/playlists/'+encodeURIComponent(p.spotify_id)+'/sync-manual',{method:'POST'});load()}}><RefreshCw size={14}/></Btn></div>)}</div></section>}
 </div>}
function Toolbar({title:Title,icon:Icon,count,onRefresh,actions}){return <div className="flex flex-wrap items-center gap-3 border-b border-white/10 p-4"><div className="flex items-center gap-2 mr-2"><Icon size={18} className="text-violet-300"/><span className="font-semibold">{Title}</span><Badge>{count}</Badge></div>{actions}<div className="ml-auto"><Btn onClick={onRefresh}><RefreshCw size={15}/></Btn></div></div>}
export default App;
